# Generated by Django 5.1.1 on 2024-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
    ]
